// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $docs_slug_ from "./routes/docs/[...slug].tsx";
import * as $gfm_css from "./routes/gfm.css.ts";
import * as $index from "./routes/index.tsx";
import * as $pycon from "./routes/pycon.tsx";
import * as $wrp_example_guest from "./routes/wrp-example-guest.tsx";
import * as $wrp_example_host from "./routes/wrp-example-host.tsx";
import * as $wrp_example from "./routes/wrp-example.tsx";
import * as $wrp_iframe_host from "./routes/wrp-iframe-host.tsx";
import * as $WrpExample from "./islands/WrpExample.tsx";
import * as $WrpExampleGuest from "./islands/WrpExampleGuest.tsx";
import * as $WrpExampleHost from "./islands/WrpExampleHost.tsx";
import * as $WrpIframeHost from "./islands/WrpIframeHost.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/docs/[...slug].tsx": $docs_slug_,
    "./routes/gfm.css.ts": $gfm_css,
    "./routes/index.tsx": $index,
    "./routes/pycon.tsx": $pycon,
    "./routes/wrp-example-guest.tsx": $wrp_example_guest,
    "./routes/wrp-example-host.tsx": $wrp_example_host,
    "./routes/wrp-example.tsx": $wrp_example,
    "./routes/wrp-iframe-host.tsx": $wrp_iframe_host,
  },
  islands: {
    "./islands/WrpExample.tsx": $WrpExample,
    "./islands/WrpExampleGuest.tsx": $WrpExampleGuest,
    "./islands/WrpExampleHost.tsx": $WrpExampleHost,
    "./islands/WrpIframeHost.tsx": $WrpIframeHost,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
