// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh manifest`.

import * as $0 from "./routes/_render.ts";
import * as $1 from "./routes/docs/[...slug].tsx";
import * as $2 from "./routes/gfm.css.ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/wrp-example-guest.tsx";
import * as $5 from "./routes/wrp-example-host.tsx";
import * as $6 from "./routes/wrp-example.tsx";
import * as $7 from "./routes/wrp-iframe-host.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/WrpExample.tsx";
import * as $$2 from "./islands/WrpExampleGuest.tsx";
import * as $$3 from "./islands/WrpExampleHost.tsx";
import * as $$4 from "./islands/WrpIframeHost.tsx";

const manifest = {
  routes: {
    "./routes/_render.ts": $0,
    "./routes/docs/[...slug].tsx": $1,
    "./routes/gfm.css.ts": $2,
    "./routes/index.tsx": $3,
    "./routes/wrp-example-guest.tsx": $4,
    "./routes/wrp-example-host.tsx": $5,
    "./routes/wrp-example.tsx": $6,
    "./routes/wrp-iframe-host.tsx": $7,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/WrpExample.tsx": $$1,
    "./islands/WrpExampleGuest.tsx": $$2,
    "./islands/WrpExampleHost.tsx": $$3,
    "./islands/WrpIframeHost.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
